services:
  - type: web
    name: musicvndow-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
